spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  h2:
    console:
      enabled: true
      path : /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Puerto del servidor
server:
  port: 8090
  servlet:
    context-path: /proyectofinal
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type:
          descriptor:
            SQL.BasicBinder: trace

    com:
      exacom:
        proyectofinal: DEBUG

