spring:
  datasource:
    url: jdbc:h2:mem:testdb_dev
    driverClassName: org.h2.Driver
    username: sa
    password: 123123
  h2:
    console:
      enabled: true
      path : /h2-console
  jpa:
    hibernate:
      ddl-auto: update
#Puerto del servidor
server:
  port: 8070
  servlet:
    context-path: /proyectofinal